<?xml version="1.0" encoding="utf-8"?><Database Name="QLKhachSan" Class="LINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=QLKhachSan;Integrated Security=True" SettingsObjectName="HotelDAL.Properties.Settings" SettingsPropertyName="QLKhachSanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietPhong" Member="ChiTietPhongs">
    <Type Name="ChiTietPhong">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaPhong" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayDatPhong" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayNhanPhong" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayTraPhong" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="LoaiHinhThue" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TrangThaiPhong" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="KhachHang_ChiTietPhong" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_ChiTietPhong" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
      <Association Name="Phong_ChiTietPhong" Member="Phong" ThisKey="MaPhong" OtherKey="MaPhong" Type="Phong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhanVien_TaiKhoan" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CMND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SDT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="KhachHang_ChiTietPhong" Member="ChiTietPhongs" ThisKey="MaKH" OtherKey="MaKH" Type="ChiTietPhong" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CMND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SDT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NhanVien_ChiTietPhong" Member="ChiTietPhongs" ThisKey="MaNV" OtherKey="MaNV" Type="ChiTietPhong" />
      <Association Name="NhanVien_TaiKhoan" Member="TaiKhoan" ThisKey="MaNV" OtherKey="MaNV" Type="TaiKhoan" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="MaPhong" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoGiuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Phong_ChiTietPhong" Member="ChiTietPhongs" ThisKey="MaPhong" OtherKey="MaPhong" Type="ChiTietPhong" />
    </Type>
  </Table>
</Database>